//详情页
exports.getIndexPage=(req,res)=>{
    res.render('detail.ejs')
}
//列表页
exports.getDetailPage=(req,res)=>{
    res.render('list.ejs')
}
//主页
exports.getListPage=(req,res)=>{
    res.render('index.ejs')
}

//后台页面部分
exports.getAdminCategoriesPage=(req,res)=>{
    res.render('admin/categories')
}
exports.getAdminCommentsPage=(req,res)=>{
    res.render('admin/comments')
}
exports.getAdminIndexPage=(req,res)=>{
    res.render('admin/index')
}
exports.getAdminLogionPage=(req,res)=>{
    res.render('admin/login')
}
exports.getAdminNavMenusPage=(req,res)=>{
    res.render('admin/nav-menus')
}
exports.getAdminPasswordResetPage=(req,res)=>{
    res.render('admin/password-reset')
}
exports.getAdminPostAddPage=(req,res)=>{
    res.render('admin/post-add')
}
exports.getAdminPostsPage=(req,res)=>{
    res.render('admin/posts')
}
exports.getAdminProfilePage=(req,res)=>{
    res.render('admin/profile')
}
exports.getAdminSettingsPage=(req,res)=>{
    res.render('admin/settings')
}
exports.getAdminSlidesPage=(req,res)=>{
    res.render('admin/slides')
}
exports.getAdminUsersPage=(req,res)=>{
    res.render('admin/users')
}
